category_names = { 
  "Ruby": "ruby",
  "Python": "python",
  "PHP": "php",
  "Perl": "perl",
  "Java": "java",
  "C/C++": "c-language",
  "Go": "go",
  "Swift": "swift",
  "JavaScript": "javaScript",
  "HTML&CSS": "html-css",
  "bash/zsh/tcsh": "shell",
  "other-language": "other-language",
  "Ruby on rails": "ruby-on-rails",
  "Django": "django",
  "Zend": "zend",
  "Symfony": "symfony",
  "CakePHP": "cake-php",
  "JSF": "jsf",
  "Struts": "struts",
  "Spring": "spring",
  "Catalyst": "catalyst",
  "other-framework": "other-framework",
  "SQL (General)": "sql",
  "Oracle Database": "oracle",
  "IBM DB2": "db2",
  "Sybase ACE": "sybase",
  "PostgreSQL": "postgresql",
  "MySQL": "mysql",
  "SQLite": "sqlite",
  "other-database": "other-database",
  "Devices": "devices",
  "TCP/IP": "tcp-ip",
  "Security": "security",
  "other-net": "other-net",
  "AWS": "aws",
  "Heroku": "heroku",
  "Salesforce": "sfdc",
  "other-cloud": "other-cloud",
  "Xen": "xen",
  "kvm": "kvm",
  "VirtualBox": "virtualbox",
  "VMWare": "vmware",
  "other-vm": "other-vm",
  "Linux": "linux",
  "Free/Open/Net BSD": "bsd",
  "MacOS": "mac",
  "Other UNIX": "other-unix",
  "Windows": "win",
  "DOS": "dos",
  "other-os": "other-os",
  "Git": "git",
  "Subversion": "subversion",
  "Redmine": "redmine",
  "Google Analytics": "google-analytics",
  "Others": "other-topics",
  }

category_names.each do |key, value|
  MainCategory.create!(
    name: key,
    name_url: value
    )
end

