default: &default
  adapter: mysql2
  encoding: utf8
  collation: utf8_bin # 文字列の大文字小文字を区別する
  pool: 5
  username: <%= ENV['MYSQL_USERNAME'] %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  socket: /var/run/mysqld/mysqld.sock
  host: <%= ENV['IP'] %>

development:
  <<: *default
  database: e_sal_development
  username: root
  password:
  socket: "/var/run/mysqld/mysqld.sock"

test:
  <<: *default
  database: e_sal_test

production:
  <<: *default
  database: e_sal_production
  username: e_sal
  password: <%= ENV['PRODUCTION_DATABASE_PASSWORD'] %>
  url: <%= ENV['DATABASE_URL'] %>
